#机器人功能设置
Ver: '1.2.2'

#消息转发
Forwarding: true

#进出提示
JoinAndLeave: true

#在线玩家查询
Online: true

#自定义回复
SDR: true

#maven仓库地址，默认为官方仓库，如速度慢或下载失败可更换为镜像仓库
#此值为空时默认使用官方仓库
Maven: "https://repo1.maven.org/maven2"